### STATUS 200
POST localhost:8080/api/good/create?projectID=1
Content-Type: application/json

{
  "name": "принтер5"
}

### STATUS 200
PATCH localhost:8080/api/good/update?projectID=2&good_id=1
Content-Type: application/json

{
  "name": "Цветок22",
  "description": "Растение"
}

### STATUS 200
POST localhost:8080//api/categories/copy_settings_category?employee_id=228
Content-Type: application/json
Authorization: Basic admin test

{
  "source_category_id": 1,
  "target_category_id": 5
}


### STATUS 200
DELETE localhost:8080/api/good/remove?projectID=2&id=1
Content-Type: application/json


### STATUS 200
GET localhost:8080/api/goods/list?limit=10&offset=0
Content-Type: application/json

### STATUS 200
PATCH localhost:8080/api/good/reprioritize?id=1
Content-Type: application/json

{
  "NewPriority": 8
}



### STATUS 200
POST localhost:8080/api/categories/move_category?employee_id=22
Content-Type: application/json
Authorization: Basic admin test

{
  "category_id": 22,
  "parent_category_id": 11
}