version: "3.8"

services:

  click:
    image: yandex/clickhouse-server:latest
    container_name: click
    ports:
      - 8123:8123  # HTTP интерфейс
      - 9000:9000  # TCP интерфейс
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_DB: direct_log

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - 4222:4222  # Порт для клиента
      - 6222:6222  # Порт для кластеризации
      - 8222:8222  # Порт для мониторинга
    volumes:
      - nats_data:/data
    command: [
      --jetstream,
      --store_dir=/data
    ]

  web:
    build: ./
    depends_on:
      - click
      - nats
    ports:
      - 8081:8081
volumes:
  clickhouse_data:
  nats_data: