version: "3.8"

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes: 
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4650
      POSTGRES_DB: default

  auth_service:
    build: ./
    depends_on:
      - postgres
    ports:
      - 8080:8080
volumes:
  dbdata: