### STATUS 200
GET localhost:8083/api/token/issue_tokens?user_id=12
Content-Type: application/json

### STATUS 200
PUT localhost:8083/api/token/update_tokens
Content-Type: application/json

{
  "access_token": "w1Q2gtQfla96P5MIUt5n77BFjPS0vHPp8pzaSCiilTU2tNDmjJvUE1IK0udrl9cf+f8a5L8Jn+v3AVluqUbuP/M/Pc+W+HODhhM2MAtjolbMsWcut7GBG5qdm68+fyPCA9PPcjXKvvkO2Av2ndxttalUexf/F9YCu3nYuXqkpZ/uWLhw8qNfWofrqIeMiaE+Z1pLw3ZfE5qIaeQU0sZS+2vnanvrWIlR/c0aH5dtJH3je8jOgL7b8s0wlWe2cYgrmWzQPVO0BmtQZTVLpTRW3BJ1yWp2LG3dxsWwqqHj3EAgDVja86b6Siiq5nff3vUDzYqhznTGWrdhfIpRVSbGsOJggb9T6ZYfp5ebp+rMmJIC+cozxP2ZFIc0WJwIdRPTtOdSnugImSg9W7b+hECgU+GnIgk1Gl5d3gnRIw7IxPpCf20+0Dp2fNb2m6931VDF+9um+AjiAuexQoRj",
  "refresh_token": "o3S9CpIcCOhJMHtMMIj3BPo2vtnKQZK1TNFImDNYW96XT2yq4AnQXP5gmlSly1ZyHJI5qSpPbwIFy1WW293YdbWDvTlxOaPKRcduq1pnu6sob9YopatgRFudzqgst05EeO7f1NXanJc+KzRjNxwkn71ezC6DdGPdmJLezJW2bA1abyARX+HhyoCIQCqTvg/Q7UTAKnF4YGcUu/XaJFmPygBMyU6HxMCJA1V3MMDFICFWNCbLLC3OH36UAw=="
}

### STATUS 200
GET localhost:8083/api/token/get_user
Content-Type: application/json

{
  "access_token": "w1Q2gtQfla96P5MIUt5n77BFjPS0vHPp8pzaSCiilTU2tNDmjJvUE1IK0udrl9cf+f8a5L8Jn+v3AVluqUbuP/M/Pc+W+HODhhM2MAtjolbMsWcut7GBG5qdm68+fyPCA9PPcjXKvvkO2Av2ndxttalUexf/F9YCu3nYuXqkpZ/uWLhw8qNfWofrqIeMiaE+Z1pLw3ZfE5qIaeQU0sZS+2vnanvrWIlR/c0aH5dtJH3je8jOgL7b8s0wlWe2cYgrmWzQPVO0BmtQZTVLpTRW3BJ1yWp2LG3dxsWwqqHj3EAgDVja86b6Siiq5nff3vUDzYqhznTGWrdhfIpRVSbGsOJggb9T6ZYfp5ebp+rMmJIC+cozxP2ZFIc0WJwIdRPTtOdSnugImSg9W7b+hECgU+GnIgk1Gl5d3gnRIw7IxPpCf20+0Dp2fNb2m6931VDF+9um+AjiAuexQoRj",
  "refresh_token": "o3S9CpIcCOhJMHtMMIj3BPo2vtnKQZK1TNFImDNYW96XT2yq4AnQXP5gmlSly1ZyHJI5qSpPbwIFy1WW293YdbWDvTlxOaPKRcduq1pnu6sob9YopatgRFudzqgst05EeO7f1NXanJc+KzRjNxwkn71ezC6DdGPdmJLezJW2bA1abyARX+HhyoCIQCqTvg/Q7UTAKnF4YGcUu/XaJFmPygBMyU6HxMCJA1V3MMDFICFWNCbLLC3OH36UAw=="
}

### STATUS 200
POST localhost:8083/api/token/logout
Content-Type: application/json

{
  "access_token": "w1Q2gtQfla96P5MIUt5n77BFjPS0vHPp8pzaSCiilTU2tNDmjJvUE1IK0udrl9cf+f8a5L8Jn+v3AVluqUbuP/M/Pc+W+HODhhM2MAtjolbMsWcut7GBG5qdm68+fyPCA9PPcjXKvvkO2Av2ndxttalUexf/F9YCu3nYuXqkpZ/uWLhw8qNfWofrqIeMiaE+Z1pLw3ZfE5qIaeQU0sZS+2vnanvrWIlR/c0aH5dtJH3je8jOgL7b8s0wlWe2cYgrmWzQPVO0BmtQZTVLpTRW3BJ1yWp2LG3dxsWwqqHj3EAgDVja86b6Siiq5nff3vUDzYqhznTGWrdhfIpRVSbGsOJggb9T6ZYfp5ebp+rMmJIC+cozxP2ZFIc0WJwIdRPTtOdSnugImSg9W7b+hECgU+GnIgk1Gl5d3gnRIw7IxPpCf20+0Dp2fNb2m6931VDF+9um+AjiAuexQoRj",
  "refresh_token": "o3S9CpIcCOhJMHtMMIj3BPo2vtnKQZK1TNFImDNYW96XT2yq4AnQXP5gmlSly1ZyHJI5qSpPbwIFy1WW293YdbWDvTlxOaPKRcduq1pnu6sob9YopatgRFudzqgst05EeO7f1NXanJc+KzRjNxwkn71ezC6DdGPdmJLezJW2bA1abyARX+HhyoCIQCqTvg/Q7UTAKnF4YGcUu/XaJFmPygBMyU6HxMCJA1V3MMDFICFWNCbLLC3OH36UAw=="
}
