### STATUS 200
GET localhost:8083/api/auth/issue_tokens?user_id=1
Content-Type: application/json

### STATUS 200
PUT localhost:8083/api/auth/update_tokens
Content-Type: application/json

{
  "access_token": "uyTNy3wD4kAMAsLuKbAs/QBcccUdTTTb4QbXZTzu1upXN+HlfvhWMrMncHSDjNKUPbhEEoj47cTlDSdnSfLwrmgnX86ONQxPzEfpmHAdjYpYCI56bGHSraqyl6k0eEHM6+vqcZQp+EfoIJStreN1P5rKxcZ7i/6VExRpA58p5F/9K4evE0XS0kf6NG/3mjGe9KXN4x7eUZoPZq60S6k3OU+xzDLPYQdWU5NjH4RqeX0GGRdGqUujiXiE3k8Af8UDZsJ/Uci607q1LVHeS+EAPqGc83teo0sjpqVk7+jbKX5KpcTjAXS+mu7aKW6RwrXLLBTOqGZcMhquBg==",
  "refresh_token": "aozBPFca5atgU+gLiLuXTWo0dy7BZlZrCj5TJgp8Li7mk+gT+dyM5pzIcVCzB/i00+Ub9AxuX8RleGAWp3cK2i4Ga0GGF/EcQ/z3GCXgTg9BZeF4lNrAZF6xnx9CE13cx+7+4qc4sjAsg7XQmMqjPFA5Lik7gBxk1SJ+l90LF/tIwu8SLZ6uFbJWtfE8adc/"
}