version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5434:5434
    volumes: 
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4650
      POSTGRES_DB: default

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass some_password
    ports:
      - 6379:6379
    volumes:
    - redis_data:/var/lib/redis
    - redis_conf:/usr/local/etc/redis/redis.conf
    environment:
    - REDIS_REPLICATION_MODE=master

  click:
    image: yandex/clickhouse-server:latest
    container_name: click
    ports:
      - 8123:8123  # HTTP интерфейс
      - 9000:9000  # TCP интерфейс
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_DB: direct_log

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - 4222:4222  # Порт для клиента
      - 6222:6222  # Порт для кластеризации
      - 8222:8222  # Порт для мониторинга
    volumes:
      - nats_data:/data
    command: [
      --jetstream,
      --store_dir=/data
    ]

  jaeger:
    image: jaegertracing/all-in-one:1.38
    ports:
      - "5775:5775"        # UDP
      - "6831:6831/udp"    # UDP
      - "6832:6832/udp"    # UDP
      - "5778:5778"        # HTTP
      - "16686:16686"      # Web UI
      - "14268:14268"      # HTTP
      - "14250:14250"      # gRPC
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  reader_to_click:
    build: ../Reader_to_click
    depends_on:
      - click
      - nats
    ports:
      - 8081:8081

  web_service:
    build: ../web_service
    depends_on:
      - jaeger
      - postgres
      - redis
      - nats
    ports:
      - 8080:8080

volumes:
  dbdata:
  redis_data:
  redis_conf:
  clickhouse_data:
  nats_data: