http:
 port: 8080

postgres:
 host: "postgres" #localhost postgres
 port: 5432
 user: "postgres"
 password: "4650"
 dbname: "postgres"
 sslmode: "disable"

redis:
 host: "redis" #localhost redis
 password: "some_password"
 port: 6379

nats:
 host: "nats:4222" #localhost
 channelName: "logs"