clickhouse:
 host: "localhost" #localhost #click
 port: 9000
 user: "user"
 password: "password"
 dbname: "direct_log"

reader:
  natsUrl: "localhost:4222" #localhost #nats
  streams:
    reader_to_click: {
      channelName: "logs_to_click",
      consumerName: "logs_to_click_consumer1",
      batchSize: 10
    }
