clickhouse:
 host: "localhost" #localhost
 port: 9000
 user: "user"
 password: "password"
 dbname: "log_buf"

nats:
 host: "cron:4222" #localhost
 channelName: "logs_to_click"
 consumerName: "logs_to_click_consumer1"

cron:
 timeSleepOnError: 60
 timeSleepOnOk: 120