clickhouse:
 host: "click" #localhost #click
 port: 8123
 user: "user"
 password: "password"
 dbname: "direct_log"

nats:
 url: "nats:4222" #localhost #nats

reader:
  reader_to_click: {
    channelName: "logs_to_click",
    consumerName: "logs_to_click_consumer1",
    timeSleepOnError: 60,
    timeSleepOnOk: 120,
  }
