port:
 port: 8081

clickhouse:
 host: "localhost" #localhost
 port: 9000
 user: "user"
 password: "password"
 dbname: "log_buf"

nats:
 host: "nats:4222" #localhost
 channelName: "logs_to_click"
 consumerName: "logs_to_click_consumer1"