clickhouse:
 host: "click" #localhost #click
 port: 8123
 user: "user"
 password: "password"
 dbname: "direct_log"

nats:
 url: "nats:4222" #localhost #nats
 channelName: "logs_to_click"
 consumerName: "logs_to_click_consumer1"

cron:
 timeSleepOnError: 60
 timeSleepOnOk: 120