CREATE TABLE IF NOT EXISTS logs (
    LogID SERIAL NOT NULL,
    GoodsID INTEGER NOT NULL,
    ProjectID INTEGER NOT NULL,
    Name character varying NOT NULL,
    Description character varying NOT NULL,
    Priority INTEGER NOT NULL DEFAULT 0,
    Removed BOOLEAN NOT NULL DEFAULT FALSE,
    EventTime TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);