name: Lint

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.0

      - name: Go_Test golangci-lint
        run: |
          echo "Текущая директория:"
          pwd
          golangci-lint run ./Go_Test/...
        

      - name: Reader_to_click golangci-lint
        run: golangci-lint run ./Reader_to_click/...
